description: Sniper Mouse Move Behavior
compatible: "zmk,behavior-sniper-mmv"

properties:
  slow-layer:
    type: int
    required: true
    description: Layer number for Slow Mode
  
  fast-layer:
    type: int
    required: true
    description: Layer number for Fast Mode
  
  delay-ms:
    type: int
    required: false
    default: 10
    description: Polling interval in ms
