description: Sniper Mouse Move Behavior
compatible: "zmk,behavior-sniper-mmv"
include: behavior-device.yaml
properties:
  slow-layer:
    type: int
    required: true
  fast-layer:
    type: int
    required: true
  base-speed:
    type: int
    required: true
    description: Base speed of the mouse
  delay-ms:
    type: int
    required: false
    default: 10
